import 'dart:ffi';
import 'dart:io';
import 'package:ffi/ffi.dart';

import 'ffi/ort_bindings.dart';
import 'dart_onnx_exception.dart';

/// Internal singleton that holds the ONNX Runtime API pointer and dynamic library.
///
/// This class manages the lifecycle of loading the ONNX Runtime shared library
/// and obtaining the OrtApi struct pointer. All high-level classes use this
/// internally to call ORT C API functions.
class OrtFFI {
  static OrtFFI? _instance;

  /// The raw FFI bindings class generated by ffigen.
  final OrtBindings bindings;

  /// The OrtApi struct containing all function pointers.
  final Pointer<OrtApi> api;

  OrtFFI._(this.bindings, this.api);

  /// Get the singleton instance, loading the library if necessary.
  static OrtFFI get instance {
    if (_instance == null) {
      final lib = _loadOrtLibrary();
      final bindings = OrtBindings(lib);
      final apiBase = bindings.OrtGetApiBase();
      final getApi = apiBase.ref.GetApi
          .asFunction<Pointer<OrtApi> Function(int)>();
      var api = getApi(ORT_API_VERSION);
      if (api == nullptr) {
        api = getApi(20); // Fallback to older widely-available version
      }
      if (api == nullptr) {
        throw DartONNXException(
          'Failed to get ORT API version $ORT_API_VERSION or 20. '
          'The ONNX Runtime library may be too old.',
        );
      }
      _instance = OrtFFI._(bindings, api);
    }
    return _instance!;
  }

  /// Check the OrtStatus returned from an API call and throw on error.
  void checkStatus(Pointer<OrtStatus> status) {
    if (status == nullptr) return; // success
    final getErrorCode = api.ref.GetErrorCode
        .asFunction<int Function(Pointer<OrtStatus>)>();
    final getErrorMessage = api.ref.GetErrorMessage
        .asFunction<Pointer<Char> Function(Pointer<OrtStatus>)>();
    final releaseStatus = api.ref.ReleaseStatus
        .asFunction<void Function(Pointer<OrtStatus>)>();

    final code = getErrorCode(status);
    final msgPtr = getErrorMessage(status);
    final message = msgPtr.cast<Utf8>().toDartString();
    releaseStatus(status);
    throw DartONNXException(message, errorCode: code);
  }

  // Library loading
  static DynamicLibrary _loadOrtLibrary() {
    // Try custom environment variable first
    final customPath = Platform.environment['DART_ONNX_LIB_PATH'];
    if (customPath != null) {
      try {
        return DynamicLibrary.open(customPath);
      } on ArgumentError {
        throw DartONNXException(
          'Could not load ONNX Runtime from DART_ONNX_LIB_PATH="$customPath".\n'
          'Verify that the file exists and is a valid ONNX Runtime shared library.',
        );
      }
    }

    // Custom fork: bind to an ONNX Runtime ALREADY loaded into this process
    // (e.g. by sherpa_onnx) instead of opening a second copy — a duplicate ORT
    // image can crash the app. DynamicLibrary.process() resolves ORT symbols
    // from the resident image when they're globally visible; fall back to
    // re-opening the versioned lib by name (dlopen refcounts → same instance).
    final proc = DynamicLibrary.process();
    if (_hasOrtSymbols(proc)) return proc;
    for (final name in const [
      'libonnxruntime.1.24.4.dylib',
      'libonnxruntime.dylib',
      'libonnxruntime.so',
    ]) {
      try {
        final lib = DynamicLibrary.open(name);
        if (_hasOrtSymbols(lib)) return lib;
      } catch (_) {}
    }

    try {
      return _openPlatformLibrary();
    } on ArgumentError {
      throw DartONNXException(
        'ONNX Runtime library not found.\n'
        '\n'
        '${_installHint()}'
        '\n'
        'Alternatively, set the DART_ONNX_LIB_PATH environment variable to the\n'
        'full path of the ONNX Runtime shared library.\n'
        '\n'
        'For more information, visit:\n'
        'https://onnxruntime.ai/docs/install/',
      );
    }
  }

  /// True if [lib] exposes the ORT entrypoint, i.e. it's a usable ONNX Runtime.
  static bool _hasOrtSymbols(DynamicLibrary lib) {
    try {
      lib.lookup<Void>('OrtGetApiBase');
      return true;
    } catch (_) {
      return false;
    }
  }

  /// Attempt to open the ONNX Runtime library using platform-specific paths.
  static DynamicLibrary _openPlatformLibrary() {
    if (Platform.isMacOS) {
      try {
        return DynamicLibrary.open('libonnxruntime.dylib');
      } catch (_) {
        // Fallback for macOS Homebrew installations on Apple Silicon
        try {
          return DynamicLibrary.open('/opt/homebrew/lib/libonnxruntime.dylib');
        } catch (_) {
          // Fallback for macOS Homebrew installations on Intel
          return DynamicLibrary.open('/usr/local/lib/libonnxruntime.dylib');
        }
      }
    } else if (Platform.isIOS) {
      return DynamicLibrary.open('libonnxruntime.dylib');
    } else if (Platform.isLinux) {
      return DynamicLibrary.open('libonnxruntime.so');
    } else if (Platform.isWindows) {
      return DynamicLibrary.open('onnxruntime.dll');
    } else if (Platform.isAndroid) {
      return DynamicLibrary.open('libonnxruntime.so');
    } else {
      throw DartONNXException(
        'Unsupported platform: ${Platform.operatingSystem}',
      );
    }
  }

  /// Return a platform-specific hint for installing ONNX Runtime.
  static String _installHint() {
    if (Platform.isMacOS) {
      return 'Install ONNX Runtime on macOS with Homebrew:\n'
          '  brew install onnxruntime\n';
    } else if (Platform.isLinux) {
      return 'Install ONNX Runtime on Linux:\n'
          '  apt install libonnxruntime  (Debian/Ubuntu)\n'
          '  — or download from the ONNX Runtime GitHub releases page.\n';
    } else if (Platform.isWindows) {
      return 'Install ONNX Runtime on Windows:\n'
          '  Download the latest release from the ONNX Runtime GitHub releases\n'
          '  page and add the directory containing onnxruntime.dll to your PATH.\n';
    }
    return '';
  }
}
